graph TD
    ide_db_work --> PySide6
    ide_db_work --> database
    ide_db_work --> tabs
    composition_manager --> PySide6
    composition_manager --> database
    ide_ui_panels --> PySide6
    ide_ui_panels --> database
    ide_main --> PySide6
    ide_main --> database
    crud_buttons --> PySide6
    ide_field_edit --> PySide6
    ide_field_edit --> database
    ide_field_edit --> widgets
    base_manager --> PySide6
    base_manager --> database
    label --> PySide6
    optiongroup --> PySide6
    __init__ --> PySide6
    textbox --> PySide6
    reference_base --> PySide6
    data_source_mixin --> PySide6
    form_container --> PySide6
    grid --> PySide6
    listbox --> PySide6
    reference --> PySide6
    container --> PySide6
    datebox --> PySide6
    button --> PySide6
    memo --> PySide6
    checkbox --> PySide6
    numberbox --> PySide6
    tab_container --> PySide6
    image_view --> PySide6
    mozart_form --> PySide6
    reference_ui --> PySide6
    combobox --> PySide6
    form --> PySide6
    data_view_tab --> PySide6
    import_tab --> PySide6
    import_tab --> database
    relations_tab --> PySide6
    base_tab --> PySide6
    base_tab --> database
    forms_tab_ui --> PySide6
    forms_tab_ui --> database
    forms_tab --> PySide6
    form_elements_widget --> PySide6
    form_elements_widget --> database
    form_elements_widget --> widgets
    class_templates_tab --> PySide6
    class_templates_tab --> database
    class_templates_tab --> widgets
    entities_tab --> PySide6
    entities_tab --> widgets
    users_roles_tab --> PySide6
    users_roles_tab --> database
    documents_tab --> PySide6
    balance_units_tab --> PySide6
    balance_units_tab --> widgets
    import_engine --> PySide6
    import_engine --> database
    import_tab --> PySide6
    import_tab --> database
    routes_tab --> PySide6
    routes_tab --> database
    import_utils --> database
    fields_tab --> PySide6
    fields_tab --> database
    composition_tab --> PySide6
    composition_tab --> database
    bu_visibility_tab --> PySide6
    bu_visibility_tab --> database
    form_wizard --> PySide6
    form_wizard --> database
    form_properties_dialog --> PySide6
    property_dialog_ui --> PySide6
    property_dialog_ui --> widgets
    live_form_designer --> PySide6
    live_form_designer --> database
    form_designer_launcher --> PySide6
    user_edit_dialog --> PySide6
    user_edit_dialog --> database
    context_tab --> PySide6
    context_tab --> database
    users_tab --> PySide6
    users_tab --> database
    menu_manager --> PySide6
    menu_manager --> database
    roles_tab --> PySide6
    roles_tab --> database
    dialogs --> PySide6
    dialogs --> database
    dialogs --> widgets
    visual_forms_tab --> PySide6
    visual_forms_tab --> widgets
    view_sqlite --> PySide6
    openDBF --> PySide6
    db_backup_tool --> PySide6
    db_backup_model --> PySide6
    packer_operations --> PySide6
    project_packer --> PySide6
    checkable_model --> PySide6
    import_engine --> database
    metadata_creator --> database
    profile_manager --> database
    mozart_matcher --> database
    import_orchestrator --> database
    relation_scene --> PySide6
    link_line --> PySide6
    graphics_view --> PySide6
    graphics_items --> PySide6
    mapping_detail_page --> PySide6
    wizard_dialogs --> PySide6
    wizard_pages --> PySide6
    wizard_pages --> database
    execute_page --> PySide6
    source_page --> PySide6
    relation_page --> PySide6
    schema_page --> PySide6
    import_wizard --> PySide6
    import_wizard --> database
    progress_dialog --> PySide6
    profile_manager_dialog --> PySide6
    profile_manager_dialog --> database
    ext_helper --> database
    field_creator --> database
    scene_profile_adapter --> database
    designer_import --> PySide6
    entity_creator --> database
    designer_mass_field_dialog --> PySide6
    designer_trees --> PySide6
    designer_v2 --> PySide6
    designer_v2 --> database
    source_ref_dialog --> PySide6
    designer_links --> PySide6
    link_edit_dialog --> PySide6
    translator --> database
    reference_selector --> PySide6
    reference_selector --> database
    reference_editor --> PySide6
    reference_editor --> database
    toolbar_bar --> PySide6
    designer_bottom_bar --> PySide6
    property_inspector --> PySide6
    scene_controls_mixin --> PySide6
    control_item_movement --> PySide6
    scene_dragdrop_mixin --> PySide6
    control_item_base --> PySide6
    palette_widget --> PySide6
    designer_widget --> PySide6
    designer_widget --> database
    scene_grid_mixin --> PySide6
    property_loader --> PySide6
    scene_loader_mixin --> PySide6
    scene_events_mixin --> PySide6
    control_item --> PySide6
    designer_controls_bar --> PySide6
    form_widget --> PySide6
    main_widget --> PySide6
    form_scene --> PySide6
    main_widget_runtime --> PySide6
    property_panel --> PySide6
    methods_panel --> PySide6
    property_editor --> PySide6
    events_panel --> PySide6
    statusbar_bar --> PySide6
    code_editor --> PySide6
    title_bar --> PySide6
    property_table --> PySide6
    designer_toolbar --> PySide6
    designer_view --> PySide6
    designer_serializer --> PySide6
    form_scene_base --> PySide6
    property_editor_base --> PySide6
    form_view --> PySide6
    designer_panels --> PySide6
    form_background --> PySide6
    resize_handle --> PySide6
    hierarchy_widget --> PySide6
    grid_manager --> PySide6
    control_item_context --> PySide6
    property_editor_sync --> PySide6